version: '3.9'

# yaml anchors to remove repeated code for setting up 'clustered services'
x-mysql-server: &mysql-server
  env_file:
    - mysql-server.env
  image: mysql/mysql-server:8.0.12
  # healthcheck:
  #   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #   timeout: 20s
  #   retries: 10

x-dbwebapp: &dbwebapp
  env_file:
    - dbwebapp.env
  build:
    context: ../
  image: local-dbwebapp
  depends_on:
    - mysql-router

services:

  mysql-server-1:
    <<: *mysql-server
    container_name: mysql-server-1
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3301:3306"
  mysql-server-2:
    <<: *mysql-server
    container_name: mysql-server-2
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
  mysql-server-3:
    <<: *mysql-server
    container_name: mysql-server-3
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"

  mysql-shell:
    container_name: mysql-shell
    env_file:
      - mysql-shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3

  mysql-router:
    container_name: mysql-router
    env_file:
      - mysql-router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server-1
      - mysql-server-2
      - mysql-server-3
      - mysql-shell
    restart: on-failure

  dbwebapp-1:
    <<: *dbwebapp
    container_name: dbwebapp-1
    ports:
      - "8081:8080"
  dbwebapp-2:
    <<: *dbwebapp
    container_name: dbwebapp-2
    ports:
      - "8082:8080"
  dbwebapp-3:
    <<: *dbwebapp
    container_name: dbwebapp-3
    ports:
      - "8083:8080"

  nginx:
    container_name: nginx
    build:
      context: nginx/.
    image: local-nginx
    ports:
      - "8080:8080"
    depends_on:
      - dbwebapp-1
      - dbwebapp-2
      - dbwebapp-3
