CREATE DATABASE db;
CREATE USER 'user'@'%' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON db.* TO 'user'@'%';
USE db;
CREATE TABLE user (
    userId INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) ENGINE=InnoDB;
INSERT INTO user (userId) VALUES (1);
